### ISSUE TITLE
Highlighting error with nested brackets

### ISSUE THREAD

**Issue by MichaelWashburnJr** [corbanmailloux/sublime-mit-alloy#5]
In some cases, you might have nested brackets. Such as the following:

```
Invariant[next[first]]
```

In this case, the rightmost bracket remains un-highlighted, and the second bracket from the right is highlighted as if it is in the outer level.  It looks to me like the highlighting rule just looks for the next `]`, which is incorrect in the case of nested brackets

**Comment by corbanmailloux** [comment]
Cool. So fix it.

**Comment by mdw7326** [comment]
I will later :p but I'm in the middle of grading now. I like reporting the
issues anyways for completeness


Michael Washburn Jr
Student, Rochester Institute of Technology
MichaelWashburnJr.com
